apps/playlist_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/edit/$',profile_edit, name='profile_edit' ),
    url(r'^playlist$', playlist, name='playlist'),
    url(r'^playlist/remove(?P<playlist_id>\d+)$', remove_playlist, name='remove')
]

apps/user_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^login/register$', index, name='home'),
    url(r'^register/$', register, name='register'),
    url(r'^auth/$',authentication, name='authentication'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^edit/$', edit, name='edit'),
    url(r'^users/$',users,name='users'),
    url(r'^follow/(?P<followee_id>\d+)$',following,name='followee'),
    url(r'^unfollow/(?P<unfollow_id>\d+)$',unfollow,name='unfollow')
]

my_music/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.views import serve

urlpatterns = [
    # url(r'^$', serve,kwargs={'path': 'index.html'}), 
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.playlist_app.urls', namespace='main')),
    url(r'^music/',include('apps.music_app.urls', namespace='music')),
    url(r'^user/', include('apps.user_app.urls', namespace='user')),
    url(r'^api/users/', include("apps.user_app.api.urls", namespace='users-api')),
]

apps/playlist_app/models.py
from __future__ import unicode_literals
from ..music_app.models import Artist,Album,Song,Fan
from ..user_app.models import User, Friend
from django.db import models

class Playlist(models.Model):
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=512)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Addition(models.Model):
    song = models.ForeignKey(Song)
    playlist = models.ForeignKey(Playlist)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Listener(models.Model):
    user=models.ForeignKey(User, related_name='favorite_playlists')
    playlist=models.ForeignKey(Playlist, related_name='listeners')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

apps/playlist_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import Playlist, Addition, Listener
# Create your views here.
def index(request):
    return render(request,'playlist_app/index.html')

def profile(request):
    return render(request,'user_app/profile.html')

def profile_edit(request):
    return render(request,'user_app/edit.html')

def playlist(request):
    if request.method=='POST':
        title=request.POST['playlist_name']
        playlist_description=request.POST['playlist_description']
        if len(title)>1:
            playlist=Playlist.objects.create(title=title, description=playlist_description)
            return redirect('main:playlist')
        else:
            messages.add_message(request,messages.ERROR, 'Title is too short')
            return redirect('main:playlist')
    context={
            'play': Playlist.objects.all()
    }

    return render(request, 'playlist_app/playlist.html', context)

def remove_playlist(request, playlist_id):
    Playlist.objects.get(id=playlist_id).delete()
    return redirect('main:playlist')

apps/playlist_app/templates/playlist_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'playlist_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Home</title>
</head>
<body>
    {% if request.session.user_id %}
    <a href="{% url 'user:logout' %}">Logout</a>&nbsp&nbsp
    <a href="{% url 'main:profile' %}" >View Profile</a>&nbsp&nbsp
    <a href="{% url 'main:playlist' %}">Add Playlist</a>&nbsp&nbsp
    {% else %}
    <a href="{% url 'user:home' %}">Login/Register</a>  
    {% endif %}
    <a href="{% url 'music:home' %}">Music</a>&nbsp&nbsp&nbsp
    <a href="{% url 'user:users' %}">Users</a>

    <h1>Hello <a href="{% url 'main:profile' %}">{{request.session.user_name}}</a>!</h1>
    
   
    
    <h2>Top 5 song!<h2><hr>
    <h2>Top 5 Artist<h2><hr>
    <h2>Top 5 Playlist<h2>
</body>
</html>

apps/playlist_app/templates/playlist_app/playlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'playlist_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Playlist</title>
</head>
<body>
    <h3><a href="{% url 'user:logout' %}">Logout</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href="{% url 'main:home' %}">Dashboard</a></h3>
    <hr>
    <h1>Playlist</h1>

    <form action="{% url 'main:playlist' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="playlist_name">
    <input type="text" name="playlist_description" row="4" cols="50">
    <input type="submit" value="Add playlist">
    </form>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    {% for playlist in play %}
        <h3><a href="">{{playlist.title}}</a>&nbsp&nbsp<a href="{% url 'main:remove' playlist_id=playlist.id %}">Remove</a></h3>
        {{playlist.description}}
    {% endfor %}
</body>
</html>