apps/music_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='home'), #music home page
    url(r'^adding$',music, name='add'), #logic for adding Artist and Albums
    url(r'^add/song/(?P<album_id>\d+)$',adding_song, name='song'), #logic for adding songs
    url(r'^add_artist/(?P<artist_id>\d+)$', add_artist, name='extra_add'),
    url(r'^album/(?P<album_id>\d+)$',album, name='albums'),#renders album for a specfic artsit
    url(r'^fan/(?P<artist_id>\d+)$',fans, name='fans')
]

apps/user_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^login/register$', index, name='home'),
    url(r'^register/$', register, name='register'),
    url(r'^auth/$',authentication, name='authentication'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^edit/$', edit, name='edit'),
    url(r'^users/$',users,name='users'),
    url(r'^follow/(?P<followee_id>\d+)$',following,name='followee'),
    url(r'^unfollow/(?P<unfollow_id>\d+)$',unfollow,name='unfollow')
]

my_music/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.views import serve

urlpatterns = [
    # url(r'^$', serve,kwargs={'path': 'index.html'}), 
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.playlist_app.urls', namespace='main')),
    url(r'^music/',include('apps.music_app.urls', namespace='music')),
    url(r'^user/', include('apps.user_app.urls', namespace='user')),
    url(r'^api/users/', include("apps.user_app.api.urls", namespace='users-api')),
]

apps/music_app/models.py
from __future__ import unicode_literals
from ..user_app.models import User,Friend
from django.db import models

class Artist(models.Model):
    name=models.CharField(max_length=64, unique=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Album(models.Model):
    title=models.CharField(max_length=64)
    artist=models.ForeignKey(Artist, related_name='albums')
    year=models.IntegerField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Song(models.Model):
    title=models.CharField(max_length=64)
    genre=models.CharField(max_length=64)
    album=models.ForeignKey(Album, related_name='songs')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Fan(models.Model):
    user=models.ForeignKey(User, related_name='favorite_artists')
    artist=models.ForeignKey(Artist, related_name='fans')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

apps/music_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import Artist,Album,Song,Fan

def index(request):#displays main music template and all music in the database
    if 'user_id' in request.session:
        context={
            'artists': Artist.objects.all()
        }
    return render(request,'music_app/index.html', context) 

def music(request):#Runs logic to add new Artist/album/year
    artist=request.POST['html_artist']
    album=request.POST['html_album']
    year=request.POST['album_year']
    auth =  True
    if len(artist)<1:
        auth = False
        messages.add_message(request,messages.ERROR,'Artist name is invalid')
    if len(album)<1:
        auth = False
        messages.add_message(request,messages.ERROR,'Album name is invalid')
    if len(year)<4 or len(year)>4:
        auth = False
        messages.add_message(request,messages.ERROR,'year is invalid')
    if auth == True:#adds everythng to the database
        try:
            artists=Artist.objects.create(name=artist)
            albums=Album.objects.create(title=album, year=year, artist_id=artists.id)
            context={
                'album_id':albums.id
            }
            url = reverse('music:song', kwargs=context)
            return redirect(url)
        except:
            messages.add_message(request,messages.ERROR,'Artist already exist')
            return redirect('music:home')     
    else:
        return redirect('music:home')

def adding_song(request, album_id):#Runs logic to add songs and renders templates
    if request.method=='POST':
        song = request.POST['html_song']
        genre = request.POST['html_genre']
        Song.objects.create(title=song, genre=genre, album_id=album_id)
        return redirect('music:song', album_id=album_id)

    context={
        'album': Album.objects.get(id=album_id),
        'songs': Song.objects.filter(album_id=album_id)
        }
    return render(request,'music_app/songs.html', context)
       
    



def add_artist(request, artist_id):#Runs login to add more albums to a specific Artist
    if request.method=='POST':
        album=request.POST['html_album']
        year=request.POST['html_year']
        
        if len(album)>1:
            Album.objects.create(title=album, year=year, artist_id=artist_id)
            return redirect('music:extra_add', artist_id=artist_id)
        else:
            messages.add_message(request,messages.ERROR,'Album name cannot be blank')
            return redirect('music:extra_add')
    context={
        'artist_id': Artist.objects.get(id=artist_id),
        'album_id': Album.objects.filter(artist_id=artist_id),
        'song_id': Song.objects.filter(album_id=artist_id)
        }
    return render(request,'music_app/artist.html', context)

def album(request, album_id):#Renders template to a specific album 
    if request.method=='POST':
        song =  request.POST['html_song']
        if len(song)>1:
            Song.objects.create(title=song, album_id=album_id)
            return redirect('music:albums', album_id=album_id)
        else:
            messages.add_message(request, messages.ERROR, 'Song name is too short')
            return redirect ('music:albums', album_id=album_id)
    context={
        'albums': Album.objects.get(id=album_id),
        'songs': Song.objects.filter(album_id=album_id)
    }
    return render(request, 'music_app/album.html', context)

def fans(request, artist_id):
    Fan.objects.create(artist_id=artist_id, user_id=request.session['user_id'])
    return redirect('music:extra_add', artist_id=artist_id )

apps/music_app/templates/music_app/album.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'playlist_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>{{albums.title}}</title>
</head>
<body>
     <h3><a href="{% url 'main:home' %}">Dashboard</a>&nbsp&nbsp&nbsp<a href="{% url 'user:logout' %}">Logout</a></h3>
    <h1>{{albums.title}} by <a href="{% url 'music:extra_add' artist_id=albums.artist.id %}">{{albums.artist.name}}</a></h1>
    
    <form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="html_song">
    <input type="submit" value="Add song">
    </form>
    {% for m in messages %}
    <p>{{m}}</p>
    {% endfor %}

     {% for song in songs %}
        <p>{{song.title}}</p>
    {% endfor %}
</body>
</html>

apps/music_app/templates/music_app/artist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'playlist_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>{{artist_id.name}}</title>
</head>
<body>
    <h3><a href="{% url 'main:home' %}">Dashboard</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href="{% url 'music:home' %}">Go Back</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href="{% url 'user:logout' %}">Logout</a></h3>
    <hr>
    <h1>{{artist_id.name}} 
    
    <a id="fan" href="{% url 'music:fans' artist_id=artist_id.id %}">Follow</a>
    
    </h1>

    <form action="{% url 'music:extra_add' artist_id=artist_id.id %}" method="POST">
    {% csrf_token %}
    Album:<input type="text" name="html_album">
    Year:<input type="text" name="html_year">
    <input type="submit" value="Add">
    </form><br>
    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}

    
    {% for album in album_id %}
    <p><a href="{% url 'music:albums' album_id=album.id %}" >{{album.title}}</a></p>
    {% for song in album.songs.all %}
    <p>{{song.title}}</p>
    {% endfor %}
    {% endfor %}
</body>
</html>

apps/music_app/templates/music_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'music_app/music.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Music</title>
</head>
<body>
    
    <h3><a href="{% url 'main:home' %}">Dashboard</a>&nbsp&nbsp&nbsp<a href="{% url 'user:logout' %}">Logout</a></h3>
    <h1>Music</h1>
    <hr>
    <form action="{% url 'music:add' %}" method="POST">

    {% csrf_token %}

    Artist:&nbsp&nbsp<input type="text" name="html_artist"><br>

    Album:<input type="text" name="html_album"><br>
    
    Year:&nbsp&nbsp&nbsp<input type="datetime" name="album_year">
    
    <input type="submit" value="Add" ><!--adding new artist and albums-->

    </form>

    {% for m in messages %}
        <p>{{m}}</p>
    {% endfor %}
    
    {% for artist in artists %}
    <div id="art">
    <h3><a href="{% url 'music:extra_add' artist_id=artist.id %}">{{artist.name}}</a></h3>
    
    <!--{% for albums in artist.albums.all %}

        <p>{{albums.title}}</p>
    
    {% endfor %}-->
    </div>
    {% endfor %}
    
    
</body>
</html>

apps/music_app/templates/music_app/songs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'playlist_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Document</title>
</head>
<body>
    <h3><a href="{% url 'music:home' %}">Go Back</a><a href="{% url 'main:home' %}">Dashboard</a></h3>
    <hr>
    <h1>Add a song</h1>

    <form action="{% url 'music:song' album_id=album.id %}"  method="POST"> <!---adding new songs-->
    {% csrf_token %}
    Song:<input type="text" name="html_song">
    Genre:<input type="text" name="html_genre">
    <input type="submit" value="Add">
    </form>

    {% for message in messages %}
        {{message}}
    {% endfor %}
</body>
</html>