apps/playlist_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/edit/$',profile_edit, name='profile_edit' ),
    url(r'^playlist$', playlist, name='playlist'),
    url(r'^playlist/remove(?P<playlist_id>\d+)$', remove_playlist, name='remove')
]

apps/user_app/api/urls.py
from django.conf.urls import url

from .views import (
    UserCreateAPIView,
    UserUpdateAPIView,
    UserListAPIView
)

urlpatterns = [

    url(r'^$',UserListAPIView.as_view(),name='List'),
    url(r'^create/$',UserCreateAPIView.as_view(),name='create'),
    url(r'^update/$',UserUpdateAPIView.as_view(),name='edit'),

    
]

apps/user_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^login/register$', index, name='home'),
    url(r'^register/$', register, name='register'),
    url(r'^auth/$',authentication, name='authentication'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^edit/$', edit, name='edit'),
    url(r'^users/$',users,name='users'),
    url(r'^follow/(?P<followee_id>\d+)$',following,name='followee'),
    url(r'^unfollow/(?P<unfollow_id>\d+)$',unfollow,name='unfollow')
]

my_music/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.views import serve

urlpatterns = [
    # url(r'^$', serve,kwargs={'path': 'index.html'}), 
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.playlist_app.urls', namespace='main')),
    url(r'^music/',include('apps.music_app.urls', namespace='music')),
    url(r'^user/', include('apps.user_app.urls', namespace='user')),
    url(r'^api/users/', include("apps.user_app.api.urls", namespace='users-api')),
]

apps/user_app/models.py
from __future__ import unicode_literals
from django.db import models

class User(models.Model):
    first_name=models.CharField(max_length=64)
    last_name=models.CharField(max_length=64)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=64)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Friend(models.Model):
    follower=models.ForeignKey(User, related_name='followees')
    followee=models.ForeignKey(User, related_name='followers')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

apps/user_app/api/views.py
from rest_framework.generics import ListAPIView, CreateAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly
)

from ..models import User
from .permissions import IsOwnerOrReadOnly
from .serializers import (
    UserSerializer, 
    UserCreateSerializer
)

class UserListAPIView(ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class UserCreateAPIView(CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserCreateSerializer

class UserUpdateAPIView(RetrieveUpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserCreateSerializer
    lookup_field = 'slug'
    permissions_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

apps/user_app/views.py
from django.shortcuts import render, reverse, redirect, HttpResponse
from django.contrib import messages
import bcrypt
import re
from .models import User, Friend

REGEX=re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

def index(request):
    return render(request,'user_app/index.html')

def authentication(request):
    html_email=request.POST['html_email']
    server_password=request.POST['html_password']

    try:
        user = User.objects.get(email=html_email)
        if user.password == bcrypt.hashpw(server_password.encode('UTF-8'), user.password.encode('UTF-8')):
            request.session['user_id'] = user.id
            request.session['user_name'] = user.first_name
            return redirect('main:home')
        else:
            messages.add_message(request,messages.ERROR,'Invalid login')
            return redirect('user:home')
                      
    except:
        messages.add_message(request,messages.ERROR,'Email does not exist')
        return redirect('user:home')

    

def register(request):
    name=request.POST['html_name']
    last_name=request.POST['html_last_name']
    email=request.POST['html_email']
    password=request.POST['html_password']
    password_confirm=request.POST['html_confirm']
    auth = True

    if len(name)<1:
        auth=False
        messages.add_message(request,messages.ERROR,'Name is too short')
    if len(name)<1:
        auth=False
        messages.add_message(request,messages.ERROR,'Last name is too short')
    if not REGEX.match(email):
        auth=False
        messages.add_message(request,messages.ERROR,'Invalid Email')
    if len(password)<8:
        auth=False
        messages.add_message(request,messages.ERROR,'password must be at least 8 characters long')
    if password!=password_confirm:
        auth=False
        messages.add_message(request,messages.ERROR,'Password do not match')
    if auth == True:
        try:
            hashed_password=bcrypt.hashpw(password.encode('UTF-8'),bcrypt.gensalt())    
            user = User.objects.create(first_name=name,last_name=last_name , email=email,  password=hashed_password)
            request.session['user_id']=user.id
            request.session['user_name']=user.first_name
            return redirect('main:home')
        except:
             messages.add_message(request,messages.ERROR,'Email already exist!')
             return redirect('user:home')

    else:
        return redirect('user:home')



def edit(request):
    first_name=request.POST['html_name']
    last_name=request.POST['html_last_name']
    password=request.POST['html_password']
    password_confirm=request.POST['html_confirm']
    auth=True
    if len(first_name)<1:
        messages.add_message(request, messages.ERROR,'Name is too short')
        auth=False
    if len(last_name)<1:
        messages.add_message(request, messages.ERROR,'Last name is too short')
        auth=False
    if len(password)<8:
        messages.add_message(request, messages.ERROR,'password must be at least 8 charecters long')
        auth=False
    if password!=password_confirm:
        messages.add_message(request, messages.ERROR,'Passwords do not match')
        auth=False
    if auth==True:
        hashed_password=bcrypt.hashpw(password.encode('UTF-8'),bcrypt.gensalt()) 
        user = User.objects.get(id=request.session['user_id'])
        user.first_name=first_name
        user.last_name=last_name
        user.password=hashed_password
        user.save()
        request.session['user_id']=user.id
        request.session['user_name']=user.first_name

        return redirect('main:home')
    else:
        return redirect('main:profile')

    return redirect('main:home')

def logout(request):
    request.session.clear()
    return redirect('main:home')
    
def users(request):
    if 'user_id' in request.session:
        user = request.session['user_id']
        context={
            'profiles': User.objects.exclude(id=user).exclude(followers__follower_id=user),
            'follow': Friend.objects.filter(follower_id=user)
        }

    return render(request, 'user_app/users.html', context)

def following(request, followee_id):
    friends = Friend.objects.create(followee_id=followee_id, follower_id=request.session['user_id'])
    return redirect('user:users')

def unfollow(request,unfollow_id):
    Friend.objects.get( followee_id=unfollow_id ,follower_id=request.session['user_id']).delete()
    return redirect('user:users')

apps/user_app/templates/user_app/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'user_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Profile Settings</title>
</head>
<body>
    <form action="{% url 'user:edit' %}" method="POST">
        {% csrf_token %} 
        <h1>Edit profile</h1>
        <p><a href="{% url 'main:home' %}">Dashboard</a></p>
        Name:<input type="text" name="html_name">
        Last Name:<input type="text" name="html_last_name">
        New Password:<input type="password" name="html_password">
        Confirm password:<input type="password" name="html_confirm">
        <input type="submit" value="Apply">
    </form>
    
    {% for m in messages %}
    {{m}}
    {% endfor %}
</body>
</html>

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'user_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Login/Register</title>
</head>
<body>
    <h1>Login/Register</h1>
    <h3><a href="{% url 'main:home' %}">Dashboard</a></h3>
     <form action="{% url 'user:authentication' %}" method="POST">
            {% csrf_token %}
            Email:<input type="email" name="html_email">
            Password:<input type="password" name="html_password"> 
        <input type="submit" value="Login">
        </form>

        <hr>
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
        <hr>

        <div id="register">
        <form action="{% url 'user:register' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="html_name">First Name<br>
            <input type="text" name="html_last_name">last Name<br>
            <input type="email" name="html_email"> Email<br>
            <input type="password" name="html_password"> Password<br>
            <input type="password" name="html_confirm"> Confirm Password<br>
            <input type="submit" value="Register">
        </form> 
        </div>  
</body>
</html>

apps/user_app/templates/user_app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'user_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>{{request.session.user_name}}</title>
</head>

<body>
    <h1>{{request.session.user_name}}</h1>
    <p><a href="{% url 'main:home' %}">Dashboard</a></p>
    <p><a href="{% url 'user:logout' %}">Logout</a></p> 
    <h2><a href="{% url 'main:profile_edit' %}" >Edit profile</a></h2>
</body>

</html>

apps/user_app/templates/user_app/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'playlist_app/main.css' %}" media="screen" title="no title" charset="UTF-8" >
    <title>Users</title>
</head>
<body>
    
    <a href="{% url 'main:home' %}">Dashboard</a>&nbsp&nbsp&nbsp&nbsp
    <a href="{% url 'user:logout' %}">Logout</a>
    <h1>{{request.session.user_name}}</h1>

    <hr>

    <h2>Following</h2>
    {% for follower in follow %}
        <p>{{follower.followee.first_name}}
        {{follower.followee.last_name}}&nbsp&nbsp&nbsp<a href="{% url 'user:unfollow' unfollow_id=follower.followee.id %}">Unfollow</a></p>
    {% endfor %}
    <hr>

    {% for user in profiles %}
        <p>{{user.first_name}}&nbsp{{user.last_name}}</p>&nbsp&nbsp&nbsp&nbsp<a href="{% url 'user:followee' followee_id=user.id %}">Follow</a>
    {% endfor %}

</body>
</html>